import React from "react";
import {
  IoPerson,
  IoSchool,
  IoRocket,
  IoBulb,
  IoEye,
  IoEyeOff,
  IoMail,
  IoCall,
  IoLocation,
  IoTime,
  IoStar,
  IoHeart,
  IoShare,
  IoBookmark,
  IoSearch,
  IoFilter,
  IoClose,
  IoCheckmark,
  IoArrowForward,
  IoArrowBack,
  IoHome,
  IoNotifications,
  IoSettings,
  IoLogOut,
  IoAdd,
  IoRemove,
  IoPlay,
  IoPause,
  IoVolumeHigh,
  IoVolumeMute,
  IoCamera,
  IoImage,
  IoDocument,
  IoDownload,
  IoUpload,
  IoTrash,
  IoEdit,
  IoCopy,
  IoLink,
  IoGlobe,
  IoWifi,
  IoBatteryFull,
  IoBatteryHalf,
  IoBatteryEmpty,
  IoLock,
  IoUnlock,
  IoShield,
  IoWarning,
  IoInformation,
  IoHelp,
  IoChatbubble,
  IoChatbubbles,
  IoVideocam,
  IoVideocamOff,
  IoMic,
  IoMicOff,
  IoHeadset,
  IoDesktop,
  IoLaptop,
  IoTabletPortrait,
  IoPhonePortrait,
  IoWatch,
  IoCar,
  IoBicycle,
  IoWalk,
  IoBus,
  IoTrain,
  IoAirplane,
  IoBoat,
  IoMap,
  IoNavigate,
  IoCompass,
  IoFlag,
  IoFlagOutline,
  IoHeartOutline,
  IoStarOutline,
  IoBookmarkOutline,
  IoShareOutline,
  IoDownloadOutline,
  IoUploadOutline,
  IoTrashOutline,
  IoEditOutline,
  IoCopyOutline,
  IoLinkOutline,
  IoGlobeOutline,
  IoWifiOutline,
  IoBatteryFullOutline,
  IoBatteryHalfOutline,
  IoBatteryEmptyOutline,
  IoLockOutline,
  IoUnlockOutline,
  IoShieldOutline,
  IoWarningOutline,
  IoInformationOutline,
  IoHelpOutline,
  IoChatbubbleOutline,
  IoChatbubblesOutline,
  IoVideocamOutline,
  IoVideocamOffOutline,
  IoMicOutline,
  IoMicOffOutline,
  IoHeadsetOutline,
  IoDesktopOutline,
  IoLaptopOutline,
  IoTabletPortraitOutline,
  IoPhonePortraitOutline,
  IoWatchOutline,
  IoCarOutline,
  IoBicycleOutline,
  IoWalkOutline,
  IoBusOutline,
  IoTrainOutline,
  IoAirplaneOutline,
  IoBoatOutline,
  IoMapOutline,
  IoNavigateOutline,
  IoCompassOutline,
} from "react-icons/io5";

// Common icons used throughout the app
export const Icons = {
  // User & Profile
  Person: (props) => <IoPerson {...props} />,
  School: (props) => <IoSchool {...props} />,

  // Navigation & Actions
  ArrowForward: (props) => <IoArrowForward {...props} />,
  ArrowBack: (props) => <IoArrowBack {...props} />,
  Close: (props) => <IoClose {...props} />,
  Checkmark: (props) => <IoCheckmark {...props} />,
  Add: (props) => <IoAdd {...props} />,
  Remove: (props) => <IoRemove {...props} />,

  // Main Navigation
  Home: (props) => <IoHome {...props} />,
  Notifications: (props) => <IoNotifications {...props} />,
  Settings: (props) => <IoSettings {...props} />,
  LogOut: (props) => <IoLogOut {...props} />,

  // Search & Filter
  Search: (props) => <IoSearch {...props} />,
  Filter: (props) => <IoFilter {...props} />,

  // Communication
  Mail: (props) => <IoMail {...props} />,
  Call: (props) => <IoCall {...props} />,
  Chatbubble: (props) => <IoChatbubble {...props} />,
  Chatbubbles: (props) => <IoChatbubbles {...props} />,

  // Media & Content
  Play: (props) => <IoPlay {...props} />,
  Pause: (props) => <IoPause {...props} />,
  VolumeHigh: (props) => <IoVolumeHigh {...props} />,
  VolumeMute: (props) => <IoVolumeMute {...props} />,
  Camera: (props) => <IoCamera {...props} />,
  Image: (props) => <IoImage {...props} />,
  Document: (props) => <IoDocument {...props} />,

  // File Operations
  Download: (props) => <IoDownload {...props} />,
  Upload: (props) => <IoUpload {...props} />,
  Trash: (props) => <IoTrash {...props} />,
  Edit: (props) => <IoEdit {...props} />,
  Copy: (props) => <IoCopy {...props} />,
  Link: (props) => <IoLink {...props} />,

  // Social & Interaction
  Heart: (props) => <IoHeart {...props} />,
  Star: (props) => <IoStar {...props} />,
  Bookmark: (props) => <IoBookmark {...props} />,
  Share: (props) => <IoShare {...props} />,

  // Location & Travel
  Location: (props) => <IoLocation {...props} />,
  Map: (props) => <IoMap {...props} />,
  Navigate: (props) => <IoNavigate {...props} />,
  Compass: (props) => <IoCompass {...props} />,
  Flag: (props) => <IoFlag {...props} />,

  // Time & Schedule
  Time: (props) => <IoTime {...props} />,

  // Technology & Devices
  Globe: (props) => <IoGlobe {...props} />,
  Wifi: (props) => <IoWifi {...props} />,
  BatteryFull: (props) => <IoBatteryFull {...props} />,
  BatteryHalf: (props) => <IoBatteryHalf {...props} />,
  BatteryEmpty: (props) => <IoBatteryEmpty {...props} />,

  // Security & Privacy
  Lock: (props) => <IoLock {...props} />,
  Unlock: (props) => <IoUnlock {...props} />,
  Shield: (props) => <IoShield {...props} />,

  // Alerts & Feedback
  Warning: (props) => <IoWarning {...props} />,
  Information: (props) => <IoInformation {...props} />,
  Help: (props) => <IoHelp {...props} />,

  // Video & Audio
  Videocam: (props) => <IoVideocam {...props} />,
  VideocamOff: (props) => <IoVideocamOff {...props} />,
  Mic: (props) => <IoMic {...props} />,
  MicOff: (props) => <IoMicOff {...props} />,
  Headset: (props) => <IoHeadset {...props} />,

  // Devices
  Desktop: (props) => <IoDesktop {...props} />,
  Laptop: (props) => <IoLaptop {...props} />,
  TabletPortrait: (props) => <IoTabletPortrait {...props} />,
  PhonePortrait: (props) => <IoPhonePortrait {...props} />,
  Watch: (props) => <IoWatch {...props} />,

  // Transportation
  Car: (props) => <IoCar {...props} />,
  Bicycle: (props) => <IoBicycle {...props} />,
  Walk: (props) => <IoWalk {...props} />,
  Bus: (props) => <IoBus {...props} />,
  Train: (props) => <IoTrain {...props} />,
  Airplane: (props) => <IoAirplane {...props} />,
  Boat: (props) => <IoBoat {...props} />,

  // Onboarding & Features
  Rocket: (props) => <IoRocket {...props} />,
  Bulb: (props) => <IoBulb {...props} />,

  // Form & Input
  Eye: (props) => <IoEye {...props} />,
  EyeOff: (props) => <IoEyeOff {...props} />,

  // Outline versions for secondary actions
  HeartOutline: (props) => <IoHeartOutline {...props} />,
  StarOutline: (props) => <IoStarOutline {...props} />,
  BookmarkOutline: (props) => <IoBookmarkOutline {...props} />,
  ShareOutline: (props) => <IoShareOutline {...props} />,
  DownloadOutline: (props) => <IoDownloadOutline {...props} />,
  UploadOutline: (props) => <IoUploadOutline {...props} />,
  TrashOutline: (props) => <IoTrashOutline {...props} />,
  EditOutline: (props) => <IoEditOutline {...props} />,
  CopyOutline: (props) => <IoCopyOutline {...props} />,
  LinkOutline: (props) => <IoLinkOutline {...props} />,
  GlobeOutline: (props) => <IoGlobeOutline {...props} />,
  WifiOutline: (props) => <IoWifiOutline {...props} />,
  BatteryFullOutline: (props) => <IoBatteryFullOutline {...props} />,
  BatteryHalfOutline: (props) => <IoBatteryHalfOutline {...props} />,
  BatteryEmptyOutline: (props) => <IoBatteryEmptyOutline {...props} />,
  LockOutline: (props) => <IoLockOutline {...props} />,
  UnlockOutline: (props) => <IoUnlockOutline {...props} />,
  ShieldOutline: (props) => <IoShieldOutline {...props} />,
  WarningOutline: (props) => <IoWarningOutline {...props} />,
  InformationOutline: (props) => <IoInformationOutline {...props} />,
  HelpOutline: (props) => <IoHelpOutline {...props} />,
  ChatbubbleOutline: (props) => <IoChatbubbleOutline {...props} />,
  ChatbubblesOutline: (props) => <IoChatbubblesOutline {...props} />,
  VideocamOutline: (props) => <IoVideocamOutline {...props} />,
  VideocamOffOutline: (props) => <IoVideocamOffOutline {...props} />,
  MicOutline: (props) => <IoMicOutline {...props} />,
  MicOffOutline: (props) => <IoMicOffOutline {...props} />,
  HeadsetOutline: (props) => <IoHeadsetOutline {...props} />,
  DesktopOutline: (props) => <IoDesktopOutline {...props} />,
  LaptopOutline: (props) => <IoLaptopOutline {...props} />,
  TabletPortraitOutline: (props) => <IoTabletPortraitOutline {...props} />,
  PhonePortraitOutline: (props) => <IoPhonePortraitOutline {...props} />,
  WatchOutline: (props) => <IoWatchOutline {...props} />,
  CarOutline: (props) => <IoCarOutline {...props} />,
  BicycleOutline: (props) => <IoBicycleOutline {...props} />,
  WalkOutline: (props) => <IoWalkOutline {...props} />,
  BusOutline: (props) => <IoBusOutline {...props} />,
  TrainOutline: (props) => <IoTrainOutline {...props} />,
  AirplaneOutline: (props) => <IoAirplaneOutline {...props} />,
  BoatOutline: (props) => <IoBoatOutline {...props} />,
  MapOutline: (props) => <IoMapOutline {...props} />,
  NavigateOutline: (props) => <IoNavigateOutline {...props} />,
  CompassOutline: (props) => <IoCompassOutline {...props} />,
  FlagOutline: (props) => <IoFlagOutline {...props} />,
};

// Default props for consistent styling
export const defaultIconProps = {
  size: 24,
  color: "#000000",
};

// Helper function to create icon with default props
export const createIcon = (IconComponent, customProps = {}) => {
  return React.createElement(IconComponent, {
    ...defaultIconProps,
    ...customProps,
  });
};

export default Icons;
